FROM registry.fedoraproject.org/fedora:40

RUN dnf update -y && \
	dnf install -y \
	bash \
	bc \
	bindgen-cli \
	bison \
	bzip2 \
	ca-certificates \
	cmake \
	ctags \
	dbus-daemon \
	diffutils \
	findutils \
	flex \
	gcc \
	gcovr \
	git \
	glib2-devel \
	glibc-langpack-en \
	hostname \
	llvm \
	make \
	meson \
	mtools \
	ninja-build \
	nmap-ncat \
	openssh-clients \
	python3 \
	python3-PyYAML \
	python3-numpy \
	python3-opencv \
	python3-pillow \
	python3-pip \
	python3-sphinx \
	python3-sphinx_rtd_theme \
	python3-zombie-imp \
	rust \
	sed \
	socat \
	sparse \
	swtpm \
	tar \
	tesseract \
	tesseract-langpack-eng \
	util-linux \
	vulkan-tools \
	which \
	xorriso \
	zstd && \
	dnf autoremove -y && \
	dnf clean all -y && \
	rm -f /usr/lib*/python3*/EXTERNALLY-MANAGED

RUN dnf update -y && \
	dnf install -y \
	mingw-w64-tools \
	mingw32-nsis \
	mingw64-SDL2 \
	mingw64-SDL2_image \
	mingw64-bzip2 \
	mingw64-curl \
	mingw64-gcc \
	mingw64-gcc-c++ \
	mingw64-gettext \
	mingw64-glib2 \
	mingw64-gnutls \
	mingw64-gtk-vnc2 \
	mingw64-gtk3 \
	mingw64-libepoxy \
	mingw64-libgcrypt \
	mingw64-libjpeg-turbo \
	mingw64-libpng \
	mingw64-libtasn1 \
	mingw64-nettle \
	mingw64-pixman \
	mingw64-pkg-config && \
	dnf clean all -y

ARG USER
ARG UID

RUN if [ "${USER}" ]; then id ${USER} 2>/dev/null || useradd -u ${UID} -U ${USER}; fi
